GET http://localhost:3000/api/phones

###

GET http://localhost:3000/api/phones?id=10

###

POST http://localhost:3000/api/phones
Content-Type: application/x-www-form-urlencoded

brand=apple&model=iphone&os=6&image=yes&screensize=8

###

DELETE http://localhost:3000/api/phones?id=10

###

PATCH http://localhost:3000/api/phones?id=13
Content-Type: application/x-www-form-urlencoded

brand=apple&model=iphone&os=6&image=yes&screensize=9

###

DELETE http://localhost:3000/api/reset

###


